export { Main } from '@/components/shared/Main'
export { Search } from '@/components/shared/Search'
export { TooltipDemo } from '@/components/shared/Tooltip'
export { Modal } from '@/components/shared/Modal'
export { LabelDemo } from '@/components/shared/LabelDemo'
export { InputOTPWithSeparator } from '@/components/shared/InputOTPWithSeparator'
export { Trash } from '@/components/shared/Trash'